### ISSUE TITLE
throw an error while analysing .sb3

### ISSUE THREAD

**Issue by Nineleven-911** [EricDing618/Scratch-To-Pygame#1]
![9D688EB95E84EA156BACC1724A2D8D0C](https://github.com/user-attachments/assets/faebd742-1949-4e85-b1ea-b7d55b029339)

**Comment by EricDing618** [comment]
I will fix it.

**Comment by Nineleven-911** [comment]
> I will fix it.

when will u fix it

**Comment by EricDing618** [comment]
> > I will fix it.
> 
> when will u fix it
> 

On Sunday every week💀
