### ISSUE TITLE
Real issue - Raise Import Error: cause by cannot import 3-Party lib which is downloaded and version is equaled

### ISSUE THREAD

**Issue by Nineleven-911** [EricDing618/Scratch-To-Pygame#3]
"D:\PycharmProjects\EricDing618 Projects\.venv\Scripts\python.exe" "D:\PycharmProjects\EricDing618 Projects\Scratch-To-Pygame-main\stp.py" 
pygame 2.5.2 (SDL 2.28.3, Python 3.12.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
You didn't install pygame,loguru,pillow or cairosvg!
Requirement already satisfied: loguru==0.7.2 in d:\pycharmprojects\ericding618 projects\.venv\lib\site-packages (from -r requirements.txt (line 1)) (0.7.2)
Requirement already satisfied: cairosvg==2.7.1 in d:\pycharmprojects\ericding618 projects\.venv\lib\site-packages (from -r requirements.txt (line 2)) (2.7.1)
Requirement already satisfied: pillow==9.5.0 in d:\pycharmprojects\ericding618 projects\.venv\lib\site-packages (from -r requirements.txt (line 3)) (9.5.0)
Requirement already satisfied: pygame==2.5.2 in d:\pycharmprojects\ericding618 projects\.venv\lib\site-packages (from -r requirements.txt (line 4)) (2.5.2)
Requirement already satisfied: colorama>=0.3.4 in d:\pycharmprojects\ericding618 projects\.venv\lib\site-packages (from loguru==0.7.2->-r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in d:\pycharmprojects\ericding618 projects\.venv\lib\site-packages (from loguru==0.7.2->-r requirements.txt (line 1)) (1.2.0)
Requirement already satisfied: cairocffi in d:\pycharmprojects\ericding618 projects\.venv\lib\site-packages (from cairosvg==2.7.1->-r requirements.txt (line 2)) (1.7.1)
Requirement already satisfied: cssselect2 in d:\pycharmprojects\ericding618 projects\.venv\lib\site-packages (from cairosvg==2.7.1->-r requirements.txt (line 2)) (0.7.0)
Requirement already satisfied: defusedxml in d:\pycharmprojects\ericding618 projects\.venv\lib\site-packages (from cairosvg==2.7.1->-r requirements.txt (line 2)) (0.7.1)
Requirement already satisfied: tinycss2 in d:\pycharmprojects\ericding618 projects\.venv\lib\site-packages (from cairosvg==2.7.1->-r requirements.txt (line 2)) (1.4.0)
Requirement already satisfied: cffi>=1.1.0 in d:\pycharmprojects\ericding618 projects\.venv\lib\site-packages (from cairocffi->cairosvg==2.7.1->-r requirements.txt (line 2)) (1.17.1)
Requirement already satisfied: webencodings in d:\pycharmprojects\ericding618 projects\.venv\lib\site-packages (from cssselect2->cairosvg==2.7.1->-r requirements.txt (line 2)) (0.5.1)
Requirement already satisfied: pycparser in d:\pycharmprojects\ericding618 projects\.venv\lib\site-packages (from cffi>=1.1.0->cairocffi->cairosvg==2.7.1->-r requirements.txt (line 2)) (2.22)

[notice] A new release of pip is available: 23.2.1 -> 24.3.1
[notice] To update, run: python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "D:\PycharmProjects\EricDing618 Projects\Scratch-To-Pygame-main\stp.py", line 202, in <module>
    main()
  File "D:\PycharmProjects\EricDing618 Projects\Scratch-To-Pygame-main\stp.py", line 192, in main
    log.debug("stp.py is running!")
    ^^^
NameError: name 'log' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\PycharmProjects\EricDing618 Projects\Scratch-To-Pygame-main\stp.py", line 208, in <module>
    log.error(e)
    ^^^
NameError: name 'log' is not defined

进程已结束，退出代码为 1

**Comment by EricDing618** [comment]
仁济，没装库和依赖软件别怪我

**Comment by EricDing618** [comment]
而且这是老版本的（都不算版本，不稳定），招笑
